### ISSUE TITLE
Feature request - `/compute/jobs/{jobid}`

### ISSUE THREAD

**Issue by pozsa** [eth-cscs/firecrest#125]
`/compute/jobs/{jobid}` should return the status of a Job directly and not a Task.
The status of the Job should be returned regardless of what the state of the job is on slurm.

**Comment by jpdorsch** [comment]
Hi @pozsa does the explanation in #124 answer this issue?

**Comment by jpdorsch** [comment]
Hi @pozsa, I will close this issue, but feel free to open it anytime if you think there's more to discuss on this issue.
Cheers.
