### ISSUE TITLE
Feature request - ability to register callback url for compute jobs

### ISSUE THREAD

**Issue by pozsa** [eth-cscs/firecrest#126]
As a client of firecrest, I would like to optionally send a callback URL with my compute job requests so that I don't have to poll firecrest for status updates.

The callback should trigger when the compute job reaches an end state (e.g. completed, failed) and return detailed information about the job.

**Comment by jpdorsch** [comment]
Hi @pozsa, thanks for your comment and really sorry for not being able to answer before.

The way we designed FirecREST is to be stateless (so we don't store client session data) and as light as possible. Including a callback will break the concept of a RESTful API. 
The idea is that your client should poll regularly for the job, the API would answer with the state of your job at the moment of the request, and the client would take care of what is triggered after a state is reached.

Hope this helps to understand our idea of the API

Cheers

**Comment by jpdorsch** [comment]
Hi @pozsa, I will close this issue, but feel free to open it anytime if you think there's more to discuss on this issue.
Cheers.

**Comment by pozsa** [comment]
Hello @jpdorsch can you explain how a callback URL breaks the restful API concept?
