### ISSUE TITLE
View of binary files

### ISSUE THREAD

**Issue by ekouts** [eth-cscs/firecrest#131]
I am basically copying this issue by @giovannipizzi from pyFirecREST: https://github.com/ekouts/pyfirecrest/issues/7

Currently, a `GET` to [/utilities/view](https://firecrest-api.cscs.ch/#/Utilities/get_utilities_view) returns a string with the given file content. Would it be possible to have a binary version of it?
E.g. if I do view of a tar.gz i get

```
Status code: 400
JSON: {'description': 'Error on head operation', 'error': "'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte"}: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```

More generally (maybe this is not intended for binary files?) it would be important also for text files, in case e.g. they were written in some other non UTF-8 encoding, that would likewise fail.

**Comment by jpdorsch** [comment]
The idea of this endpoint is to see the content of a plain text file, thinking on the use case of checking what is being written in SLURM output or error files, or to show configuration files of a simulation, for instance.

I wouldn't use this to check the content of a binary file, moreover, if you try to see the content of a binary file without specific software you would get bytes without proper encoding (I guess).

In the case you are mentioning, we can try to include UTF-8 files in the same endpoint.

**Comment by jpdorsch** [comment]
This was clarified in the openapi doc here https://github.com/eth-cscs/firecrest/blob/81d60f0c21ca0632497bd60c36fbe081614052ca/doc/openapi/firecrest-developers-api.yaml#L1142
