### ISSUE TITLE
API Request speed

### ISSUE THREAD

**Issue by louisponet** [eth-cscs/firecrest#162]
Hi All,

I have played around a little with the FireCREST api, and I found it to be relatively slow. I was wondering why this is the case. 

Some examples:
`cat file`:
- through ssh: 2.4 seconds
- through FireCREST view: 2.1 seconds

`ls -la`:
- through ssh: 2.4 seconds
- through FireCREST: 0.98 seconds

I have been using a restAPI server on daint's frontend which I talk with through an ssh tunnel (I suspect this is where most of the speed increase comes from), and performing a restAPI request similar to `ls` only takes 0.0065 seconds. 

Is this known? If so, what is the source of this difference? It seems FireCREST is on average slightly faster than through `ssh` calls, but I expected that it could be much faster. 
Is there a plan to improve the speed? 

Cheers,
Louis

**Comment by aledabin** [comment]
Hi Louis,

Thanks for your interest on FirecREST :)  there are some things that may affect performance:
1. FirecREST uses SSH to connect from the microservice to the machine that executes the command (`ls`, `sbatch`, etc), so there is time consumed there. A call to `/status/parameters` does not make any SSH connection and should not be over 0.2s (including point 3), usually lower.
2. `ls` depends on the filesystem load and directory size, so time can vary. But the time can also be different if you repeat the operation within some seconds as the filesystem can cache the result.
3. each time PyFirecREST (or an app/script where you provide your credentials) runs it has to contact Keycloak to authenticate, receive a token, and then it makes the request(s) to the FirecREST service. PyFirecREST caches the authentication token while it is running and reuses it, but the token has to be renew every 5 minutes anyway.

When you execute through an SSH tunnel, the SSH connection and authentication are already done, FirecREST can not provide the same speed. However, we may have to look at some ways to reduce the impact of (1).

Hope this clarifies how it works, and please let us know if not, or if you have any other question/comment/suggestion.

Best,
Alejandro

**Comment by louisponet** [comment]
Hi Alejandro,

Yes that clarifies things. I suspect that point 1 is the main culprit
indeed.

Would one "quick and hacky" way to test this be to construct an ssh tunnel
between the machine on which the microservice runs and one of the frontends
and route ssh commands through that?

I was indeed also caching the authentication, so point 3 probably didn't
play a big role.

Best regards,
Louis

**Comment by aledabin** [comment]
Hi Louis, do you still see issues with API speed ? 
We're working to speedup it but will be for later in the year.

**Comment by aledabin** [comment]
Hi Louis, I'm closing this but feel free to reopen if you see the issue.
Best,
