### ISSUE TITLE
whoami and home endpoints

### ISSUE THREAD

**Issue by chrisjsewell** [eth-cscs/firecrest#169]
Heya, unless I'm missing anything, I don't see anyway for you to get who you are and what your home directory is?

**Comment by jpdorsch** [comment]
Hi @chrisjsewell, thanks for your comment. Is actually a good idea. 
We will look to implement this in the API. 
Cheers

**Comment by jpdorsch** [comment]
Hi @chrisjsewell ,

This is solved in [1.11.0](https://github.com/eth-cscs/firecrest/releases/tag/v1.11.0)

For $HOME directory, it will depend on the filesystems that are exposed in your FirecREST implementation.
You can check those in /status/parameters endpoint https://firecrest-api.cscs.ch/#/Status/get_status_parameters. 
In cases like CSCS implementation, $HOME directory is not mounted for security reasons, therefore you will have to use a combination of the filesystems exposed and the username.

I will close the issue but feel free to open it again if needed

Best regards
