### ISSUE TITLE
/storage/xfer-external/upload: targetPath should include the filename

### ISSUE THREAD

**Issue by chrisjsewell** [eth-cscs/firecrest#174]
From https://firecrest-api.cscs.ch/#/Storage/post_storage_xfer_external_upload, it is not really clear that the filename of the uploaded path is actually taken from `sourcePath`: https://github.com/eth-cscs/firecrest/blob/1db855268bb485212c7cb9a5d5ea3528d2c8b62c/src/storage/storage.py#L219

(the method of getting the filename on this line also assumes that the `sourcePath` is POSIX)

I would suggest that actually it should be taken from `targetPath`, which should be the full path, not just directory.
`sourcePath` should really not even be required since it works perfectly fine without, if you don't need the curl command.

As an example, using pyfirecrest and aiohttp:

```python
filename = "filename.txt"
file_bytes = b"hallo world"

up_obj = client.external_upload(
    client_row.machine_name, filename, "/path/on/remote"
)
params = up_obj.object_storage_data["parameters"]
async with aiohttp.ClientSession() as session:
    form = aiohttp.FormData()
    form.add_field("file", file_bytes, filename=filename)
    for key, value in params["data"].items():
        form.add_field(key, value)
    async with session.post(
        params["url"],
        data=form,
        headers=params["headers"],
        params=params["params"],
    ) as resp:
        return await resp.text()
```

Here, I never actually have a file on disk.

**Comment by aledabin** [comment]
Hi @chrisjsewell, thanks, we'll address it

**Comment by jpdorsch** [comment]
Hi @chrisjsewell, this should be fixed now in the our newest release https://github.com/eth-cscs/firecrest/releases/tag/v1.13.0.

Let us know if this fixes your issue,

Cheers

**Comment by jpdorsch** [comment]
Hi @chrisjsewell since I don't have a confirmation from you, I will closed this issue, and if you think we still need to work on it, please feel free to re-open it.

Thanks, 
Cheers
