### ISSUE TITLE
Different System Where My Slurm Resides

### ISSUE THREAD

**Issue by scavenqqer** [eth-cscs/firecrest#176]
Can you anyone suggest or help on this. 

![image](https://user-images.githubusercontent.com/117581253/217756848-718bd6b7-eaff-4eea-8ba2-da3a5792ebd3.png)

Thank you.

**Comment by jpdorsch** [comment]
Hi @scavenqqer ,

Could you give us more information on this? for instance, how did you configure FirecREST env to add `coare` system?

Thanks,

Cheers

**Comment by scavenqqer** [comment]
Hello @jpdorsch 

I change the common.env as per the instruction to test to my cluster. 

[https://github.com/eth-cscs/firecrest/tree/master/deploy/demo](url)

![image](https://user-images.githubusercontent.com/117581253/217969215-d622911d-caea-4e6f-9402-a7ec1fe2cc0c.png)
Thank you.

**Comment by jpdorsch** [comment]
Ok, now what that configuration does is add your system to be part of FirecREST. But this doesn' t mean the cluster is reachable via FirecREST. The VM where you installed FirecREST has to be able to reach the cluster via port 22 (SSH). This is configured in the variables:

```
F7T_SYSTEMS_INTERNAL_COMPUTE='<dns_or_ip_of_cluster>:<port_ssh>;<another_dns_or_ip_of_cluster>:<port_ssh>'
F7T_SYSTEMS_INTERNAL_STORAGE='<dns_or_ip_of_cluster>:<port_ssh>;<another_dns_or_ip_of_cluster>:<port_ssh>'
F7T_SYSTEMS_INTERNAL_UTILITIES='<dns_or_ip_of_cluster>:<port_ssh>;<another_dns_or_ip_of_cluster>:<port_ssh>'
```

As you can see in the examples, the format is <DNS or IP>:<port where SSH is running>

Hope this helps
Cheers

**Comment by scavenqqer** [comment]
Hello @jpdorsch 

Thank you for the response.
Actually it is already adjusted.

![image](https://user-images.githubusercontent.com/117581253/218048304-deb83fc4-2ac8-403b-bb0e-64afe883036e.png)

It is pointed to my Cluster IP.

**Comment by scavenqqer** [comment]
Also, I cannot adjust ssh config of the cluster. So I just created a _SSH KEY TYPE RSA_ in my VM and append the _Pub key_ on the Cluster.

Could there be another solution ? or is it correct already ?

**Comment by jpdorsch** [comment]
> Hello @jpdorsch
> 
> Thank you for the response. Actually it is already adjusted.
> 
> ![image](https://user-images.githubusercontent.com/117581253/218048304-deb83fc4-2ac8-403b-bb0e-64afe883036e.png)
> 
> It is pointed to my Cluster IP.

Ok, the configuration is fine, now for this part I will ask you to check if it' s possible to reach port 22 of your cluster from the containers of FirecREST (this is, from the VM where FirecREST is installed).

You can check this executing netcat (for instance) from the VM: `nc -nv 202.0.0.0 22` and you should get something like `tcp succeded!`

**Comment by scavenqqer** [comment]
> > Hello @jpdorsch
> > Thank you for the response. Actually it is already adjusted.
> > ![image](https://user-images.githubusercontent.com/117581253/218048304-deb83fc4-2ac8-403b-bb0e-64afe883036e.png)
> > It is pointed to my Cluster IP.
> 
> Ok, the configuration is fine, now for this part I will ask you to check if it' s possible to reach port 22 of your cluster from the containers of FirecREST (this is, from the VM where FirecREST is installed).
> 
> You can check this executing netcat (for instance) from the VM: `nc -nv 202.0.0.0 22` and you should get something like `tcp succeded!`

Whoooooo.

It failed . 
![image](https://user-images.githubusercontent.com/117581253/218067192-75af11de-00bd-420d-a4df-79ddafc292b2.png)

**Comment by scavenqqer** [comment]
Hello @jpdorsch ,

It still not connected to my cluster after adding the ssh keys. BTW I used RSA type key.

Its also connected to the other cluster.

![image](https://user-images.githubusercontent.com/117581253/218632157-e0d4c87f-466a-44e8-8148-1a4a528860a7.png)

![image](https://user-images.githubusercontent.com/117581253/218632005-b1b068e6-af4c-4310-9289-5eb65a9f0003.png)

Is there any more to change ? 
Thank you.

**Comment by jpdorsch** [comment]
Hi @scavenqqer ,

The way that FirecREST handles SSH connections from microservices to the cluster is by using a Certificate Authority microservice (`certificator`) and making the cluster's SSH configuration trust the `certificator` signed certificates.

Basically, you have 2 pairs of keys (as you can see in https://github.com/eth-cscs/firecrest/tree/master/deploy/test-build/environment/keys)
- `ca_key` (private) and `ca_key.pub` (public)
- `user-key` (private) and  `user-key.pub` (public)

You will have to create these 2 pairs, and then mount them in the containers as is in the demo environment.

Now, for the cluster you will need to configure SSH as you can see in the repo for the demo cluster (https://github.com/eth-cscs/firecrest/blob/f9034c71d6651c372f79bd56a65f10395c050d35/deploy/test-build/cluster/ssh/sshd_config#L101)

```
Match Address 192.168.0.0/16 
    TrustedUserCAKeys /etc/ssh/ca-key.pub
    # only accept this CA, and not regular priv/pub SSH keys
    PubkeyAcceptedKeyTypes ssh-rsa-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com
    PermitRootLogin  no
    #DenyGroups root bin admin sys
    #AllowUsers user1
    MaxAuthTries 1
    AllowTcpForwarding no
    ForceCommand /ssh_command_wrapper.sh
    PermitTTY no
    PermitTunnel no
```

- In `MatchAddress` you have to put the IP address or DNS of the VM where the microservices are running.
- In `TrustedUserCaKeys` the path to the public key part of the certificate authority machine

**Comment by scavenqqer** [comment]
> Hi @scavenqqer ,
> 
> The way that FirecREST handles SSH connections from microservices to the cluster is by using a Certificate Authority microservice (`certificator`) and making the cluster's SSH configuration trust the `certificator` signed certificates.
> 
> Basically, you have 2 pairs of keys (as you can see in https://github.com/eth-cscs/firecrest/tree/master/deploy/test-build/environment/keys)
> 
> * `ca_key` (private) and `ca_key.pub` (public)
> * `user-key` (private) and  `user-key.pub` (public)
> 
> You will have to create these 2 pairs, and then mount them in the containers as is in the demo environment.
> 
> Now, for the cluster you will need to configure SSH as you can see in the repo for the demo cluster (
> 
> https://github.com/eth-cscs/firecrest/blob/f9034c71d6651c372f79bd56a65f10395c050d35/deploy/test-build/cluster/ssh/sshd_config#L101
> 
> )
> ```
> Match Address 192.168.0.0/16 
>     TrustedUserCAKeys /etc/ssh/ca-key.pub
>     # only accept this CA, and not regular priv/pub SSH keys
>     PubkeyAcceptedKeyTypes ssh-rsa-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com
>     PermitRootLogin  no
>     #DenyGroups root bin admin sys
>     #AllowUsers user1
>     MaxAuthTries 1
>     AllowTcpForwarding no
>     ForceCommand /ssh_command_wrapper.sh
>     PermitTTY no
>     PermitTunnel no
> ```
> 
> * In `MatchAddress` you have to put the IP address or DNS of the VM where the microservices are running.
> * In `TrustedUserCaKeys` the path to the public key part of the certificate authority machine

If this part is not possible to change on the cluster, since it is using the RSA type keys for connection. How can it integrate with the FirecREST ?

**Comment by scavenqqer** [comment]
@jpdorsch  

I've tried to test it with another system/cluster and with the use of 2 pairs of keys.
but it tells invalid path after creating user on that system/cluster.

![image](https://user-images.githubusercontent.com/117581253/219312704-56720f91-c8b4-4f65-bb66-fa6c97e5f3c7.png)
