### ISSUE TITLE
[Feature request] Allow previewing file contents

### ISSUE THREAD

**Issue by simonbray** [eth-cscs/firecrest#177]
Hello, we are using FirecREST to schedule scientific workflows onto CSCS resources. The output files, and even the log files, for intermediate steps are too big to download, but under some circumstances it could be nice to see a preview of the files to reassure the user that the output is as expected. But this doesn't seem possible with FirecREST at the moment, without downloading the entire file.

Looking at the code, I see that the `view` endpoint (https://github.com/eth-cscs/firecrest/blob/028edf3bf492c803f4033753f80f61e6747ce248/src/utilities/utilities.py#L231) already makes use of the `head` command. So hopefully this could be very easy to implement, just a matter of exposing the maximum file size parameter on the API :)

**Comment by aledabin** [comment]
Hello @simonbray , thank you for the suggestion. Yes, it can be useful and will be implemented, we will let you know when it is deployed.

**Comment by simonbray** [comment]
Great, thanks a lot!

**Comment by aledabin** [comment]
Hi @simonbray 
This was included in [1.11.0](https://github.com/eth-cscs/firecrest/releases/tag/v1.11.0)
Best,

**Comment by simonbray** [comment]
Thank you @aledabin, that was quick! I guess you have not deployed it yet? Let me know if you would like me to test.

**Comment by aledabin** [comment]
No, It will take some days to get into production, I'll let you know.

**Comment by aledabin** [comment]
Hi @simonbray , changes were deployed on the last maintenance.

**Comment by simonbray** [comment]
Thank you @aledabin!
