### ISSUE TITLE
Uploading file with FirecREST to a different file name doesn't work?

### ISSUE THREAD

**Issue by simonbray** [eth-cscs/firecrest#178]
```
>>> file_upload = client.external_upload('daint', '/path/to/file.txt', '/cscs_path/to/renamed_file.txt')
...
HeaderException: last request: 400 {'description': 'sourcePath error'}: /cscs_path/to/renamed_file.txt is an invalid path.
```

My solution is

```
>>> os.symlink('/path/to/file.txt', '/path/to/renamed_file.txt')
>>> file_upload = client.external_upload('daint', '/path/to/renamed_file.txt', '/cscs_path/to/')
```
but this is a bit awkward in my opinion.

**Comment by aledabin** [comment]
Hi @simonbray, thanks, we'll address it.

**Comment by jpdorsch** [comment]
Hi @simonbray, this should be fixed in new release https://github.com/eth-cscs/firecrest/releases/tag/v1.13.0.
Let me
 know if this works for you,
Cheers

**Comment by jpdorsch** [comment]
Hi @simonbray, since I don't have a confirmation from you, I will closed this issue, and if you think we still need to work on it, please feel free to re-open it.

Thanks, 
Cheers

**Comment by simonbray** [comment]
Hi @jpdorsch, I'm afraid I didn't have time to test this yet, but thank you for implementing it as a feature! No need to reopen it.
