### ISSUE TITLE
acct endpoint doesn't verify input is a list

### ISSUE THREAD

**Issue by simonbray** [eth-cscs/firecrest#180]
I wanted to search for a single job and wrongly entered it as a string rather than a list, and got this output
```
>>> client.poll("daint", "43302819")
>>> [{'exit_code': '0:0',
  'jobid': '2',
  'name': 'rfm_HelloTest_job',
  'nodelist': 'None assigned',
  'nodes': '1',
  'partition': 'cscsci',
  'start_time': 'Unknown',
  'state': 'PENDING',
  'time': '00:00:00',
  'time_left': 'Unknown',
  'user': 'jenscscs'},
 {'exit_code': '0:0',
  'jobid': '3',
  'name': 'rfm_HelloTest_job',
  'nodelist': 'None assigned',
  'nodes': '1',
  'partition': 'cscsci',
  'start_time': 'Unknown',
  'state': 'PENDING',
  'time': '00:00:00',
  'time_left': 'Unknown',
  'user': 'jenscscs'}]
```

so it seems the input is being iterated over without verifying it's a list.

**Comment by ekouts** [comment]
Hey Simon, I think this should be an issue in pyfirecrest, instead of firecrest, but we can discuss here anyway.
To be honest I saw it more as a feature than a bug. I didn't check the type of the argument on purpose so that users can pass any iterable (like tuples, sets etc). On the other hand specifically the string can be misleading and create issues, like in your case so I will disallow strings. If you think of any other type that could cause issues let me know.

**Comment by simonbray** [comment]
> Hey Simon, I think this should be an issue in pyfirecrest, instead of firecrest, but we can discuss here anyway. To be honest I saw it more as a feature than a bug. I didn't check the type of the argument on purpose so that users can pass any iterable (like tuples, sets etc). On the other hand specifically the string can be misleading and create issues, like in your case so I will disallow strings. If you think of any other type that could cause issues let me know.

Yes, makes sense :+1:

I don't know if you ever intend to add explicit typing to pyfirecrest, but it would be helpful for this kind of issue.

**Comment by ekouts** [comment]
Hi Simon, we decided to put a simple warning (https://github.com/eth-cscs/pyfirecrest/pull/54) in the end for strings. I will close the issue but feel free to open another one in pyfirecrest if you would like a different behavior. :)

**Comment by simonbray** [comment]
> Hi Simon, we decided to put a simple warning ([eth-cscs/pyfirecrest#54](https://github.com/eth-cscs/pyfirecrest/pull/54)) in the end for strings. I will close the issue but feel free to open another one in pyfirecrest if you would like a different behavior. :)

Thanks!
