### ISSUE TITLE
Sbatch Error 

### ISSUE THREAD

**Issue by komraad** [eth-cscs/firecrest#185]
Good Day,

I use to 2 commands to see the details on the cluster using the FirecREST. But it prompted an error. 
<img width="745" alt="image" src="https://github.com/eth-cscs/firecrest/assets/117581253/1b6aa3b0-c59f-4580-abdc-4634132c5174">

This is the result. 

<img width="690" alt="image" src="https://github.com/eth-cscs/firecrest/assets/117581253/20a41cab-c303-4f0a-8bcf-f734d9a4e157">

I was using version 1.11.1

Thanks.

**Comment by aledabin** [comment]
Hi @scavenqqer,
Slurm complains the submitted file has DOS/Windows line breaks instead of Unix line breaks. It is usually possible to convert between them with a text editor on Windows.

**Comment by scavenqqer** [comment]
Hello @aledabin 

May I know any suggestions on where to change/convert ? is it on the script? or on a browser running firecrest?
If it is on the script. Which script should be change.
Thank you.
