### ISSUE TITLE
File Uploading

### ISSUE THREAD

**Issue by scavenqqer** [eth-cscs/firecrest#186]
Hello,

Error while uploading small file using FirecREST in browser.
<img width="702" alt="image" src="https://github.com/eth-cscs/firecrest/assets/117581253/39fd2292-9607-42c5-83bf-5d3ff59261c1">

Thank you.

**Comment by jpdorsch** [comment]
Hi @scavenqqer, unfortunately we are not currently supporting the demo GUI web client for FirecREST.
In the future, this will be replaced by another more complete client.

Kindly, check the notes in future releases for this new FirecREST GUI development.

Sorry for not being clear in the documentation on the demo client, we will try to address it in the future.

Cheers

**Comment by jpdorsch** [comment]
Hi @scavenqqer this should be fixed in the new release https://github.com/eth-cscs/firecrest/releases/tag/v1.13.1,

Cheers
