### ISSUE TITLE
Include `X-Size-Limit` in `doc/openapi`

### ISSUE THREAD

**Issue by chrisjsewell** [eth-cscs/firecrest#192]
For `utilities/view` and `utilities/download`

**Comment by jpdorsch** [comment]
Hi @chrisjsewell , this was included in [current release](https://github.com/eth-cscs/firecrest/releases/tag/v1.13.1).
Let us know if this solves this issue.
Cheers

**Comment by jpdorsch** [comment]
Closing this issue.
