### ISSUE TITLE
Feature request: provide the deployed FirecREST version on the server

### ISSUE THREAD

**Issue by khsrali** [eth-cscs/firecrest#204]
Some features of FirecREST are not available in older versions. 
It would be helpful to include the deployed version, possibly along with `/status/parameters`, so we can control which endpoints to use and avoid discovery with trail calls :100:

**Comment by jpdorsch** [comment]
Hi @khsrali ,
We for sure will evaluate this, thanks for the request!
Cheers

**Comment by jpdorsch** [comment]
Hi @khsrali ,

The feature has been added to [GET /status/parameters](https://github.com/eth-cscs/firecrest/blob/master/src/status/status.py#L621).

You can see the JSON fields on the [CHANGELOG](https://github.com/eth-cscs/firecrest/blob/master/CHANGELOG.md#added) file.

Cheers

**Comment by khsrali** [comment]
Thanks a lot @jpdorsch 
We adopted:
https://github.com/aiidateam/aiida-firecrest/pull/60

Cheers
